### ISSUE TITLE
changement video

### ISSUE THREAD

**Issue by matthieu-farcot** [Error-Cezar/VR-Project#1]
Hello

Merci de mettre une vidéo plus gentillette pour usage en interne à des fins de démo.

Pas de gunfight stp.

**Comment by matthieu-farcot** [comment]
Tu n'as qu'à utiliser cette video https://archive.org/details/dramaticchipmunk

**Comment by matthieu-farcot** [comment]
A toi de me dire comment tu auras réussi a la télécharger depuis archive.org (indice: cherche le format video approprié dans le code source de la page indiquée plus haut)

**Comment by Error-Cezar** [comment]
Hi!
Sorry for the late answer but said video have been changed to what you have requested.
Have a nice day or night, whatever time it is currently
