### ISSUE TITLE
rayons lumineux page d'accueil

### ISSUE THREAD

**Issue by matthieu-farcot** [Error-Cezar/VR-Project#4]
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Rayons lumineux éclairant le ciel à l'horizon</title>
    <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
  </head>
  <body>
    <a-scene>
      <a-entity position="0 0 -10">
        <a-entity position="-10 0 0" rotation="0 0 0">
          <a-entity light="type: point; intensity: 2; distance: 100; decay: 1; color: #ff0000" animation="property: position; to: 10 0 0; dur: 2000; easing: linear; loop: true"></a-entity>
        </a-entity>
        <a-entity position="10 0 0" rotation="0 0 0">
          <a-entity light="type: point; intensity: 2; distance: 100; decay: 1; color: #00ff00" animation="property: position; to: -10 0 0; dur: 2000; easing: linear; loop: true"></a-entity>
        </a-entity>
        <a-entity position="0 0 10" rotation="0 0 0">
          <a-entity light="type: point; intensity: 2; distance: 100; decay: 1; color: #0000ff" animation="property: position; to: 0 0 -10; dur: 2000; easing: linear; loop: true"></a-entity>
        </a-entity>
      </a-entity>
    </a-scene>
  </body>
</html>

**Comment by Error-Cezar** [comment]
``
